### ISSUE TITLE
Search function Problem

### ISSUE THREAD

**Issue by marvoh** [maidmaid/zoho#1]
Hi, 

I'm trying to return tasks based on owner paramemer as below but keep getting an error

`$records = $client->searchRecords('Tasks',$criteria = ['Task Owner' => 'James Bond']);`

Error:

`Unable to process your request. Please verify if the name and value is appropriate for the "criteria" parameter.`

How can I retrieve these records?

**Comment by maidmaid** [comment]
Hello @marvoh! Example in the doc is bad. Try instead ``$criteria = '(Task Owner:James Bond)'``.

**Comment by maidmaid** [comment]
See [official doc](https://www.zoho.eu/crm/help/api/searchrecords.html) for full details of ``criteria`` field.
