### ISSUE TITLE
Code fails with text containing newlines

### ISSUE THREAD

**Issue by blacknell** [maidmaid/zoho#4]
If you send a string with a newline in it (such as for description), then the code fails and throws an error. It seems the serialiser needs to wrap such text in a CDATA so ZoHo can handle it
 
`$client = new Client(NOMAD_ZOHO_AUTHENTICATION);
$lead = [
    1 => [
        'First Name' => $firstname,
        'Last Name' => $lastname,
        'Email' => $email_address,
        'Phone' => $phone_number,
        'Description' => sprintf("hello\nthere".'&'), // the & forces a CDATA wrapper
        'Lead Source' => 'Website',
       ]
];
$result = $client->insertRecords($module = 'Leads', $lead);`

**Comment by maidmaid** [comment]
Could you give me the message returned by Zoho?

**Comment by maidmaid** [comment]
Normally, that's fixed now.
